[theme]
base="light"

button[kind="primary"] {
    background-color: rgb(240, 103, 137);
    height: auto;
    width: 200px;
    padding-top: 10px !important
    padding-bottom: 10px !important;
}

button[kind="secondary"] {
    background-color: rgb(214, 211, 169);
    height: auto;
    width: 200px;
    padding-top: 10px !important
    padding-bottom: 10px !important;
}
